### ISSUE TITLE
Tags content fixes

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#513]
Gather all tags content fixes to this task:

- [ ] (#554) Business said, that [this category](https://www.stroyprombeton.ru/gbi/categories/473/) contains options, that recently was not active products
- [ ] (#555) Template code on the category presented ahead. Screen: http://prntscr.com/n1tjku
- [ ] (#556) Remove high-level categories layer
- [x] Can't reproduce ~Some category-tag pages contains no positions https://www.stroyprombeton.ru/gbi/categories/47/tags/seriia__seriia-3_407_1_144_-vypusk-1/~
- [x] Can't reproduce ~[This category](https://www.stroyprombeton.ru/gbi/categories/463/) opens slowly with a fresh cache~

**Comment by duker33** [comment]
created subtasks for every fix from this set
